### ISSUE TITLE
Data does not match to PrivateKeyInfo ASN1 schema

### ISSUE THREAD

**Issue by VaLThieL** [PeculiarVentures/xadesjs#107]
I'm ujsing the XAdES-EPES signature example, and got this error for the

crypto.subtle.importKey("pkcs8", keyDer, alg, false, ["sign"]);

part, any clue?

and change this line

xadesjs.Application.setEngine("NodeJS", );

for

xadesjs.Application.setEngine("NodeJS", crypto);

beacause it wasn't working

**Comment by davidwr** [comment]
Same issue here!

My certificate sign algorithm is SHA-256RSA and hash sha-256.

**Comment by microshine** [comment]
@davidwr What crypto module do you use in NodeJS?

You can use `@peculiar/webcrypto` for example
```js
import { Crypto } from "@peculiar/webcrypto";

const crypto = new Crypto();
```

Is your PKCS8 private key unencrypted?

It must look like
![image](https://user-images.githubusercontent.com/7333669/94696373-a621fb80-033f-11eb-961e-7de17e861c4b.png)

Use [ASN.1 decoder](https://lapo.it/asn1js) to decode your key

**Comment by davidwr** [comment]
Thanks for the fast response!

Yeah, I'm using like that:

```javascript
var { Crypto } = require("@peculiar/webcrypto");
const crypto = new Crypto();
```

My private key is in the format:
```
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAiFWMNbY6Q...
```

I try to use the website you suggest but I can't export the generated data, event using the Developers inspect element hehe
How I do that?

**Comment by microshine** [comment]
https://codesandbox.io/s/issue-107-qk7vb?file=/src/index.js

![image](https://user-images.githubusercontent.com/7333669/94703955-0f0d7180-0348-11eb-97c6-0e80c2c377e0.png)

**Comment by davidwr** [comment]
I'm using node v12.18.0

**Comment by davidwr** [comment]
Hey @VaLThieL @microshine !

I follow this [example](https://codesandbox.io/s/xadesjs-issue-78-o00ez?file=/index.js:0-6641), and it works!!

Thanks!
