### ISSUE TITLE
Truncated signd XML

### ISSUE THREAD

**Issue by chronorus** [PeculiarVentures/xadesjs#109]
[DS Detected signedXML.xml.txt](https://github.com/PeculiarVentures/xadesjs/files/5331557/DS.Detected.signedXML.xml.txt)
Hi, I am facing a curios scenario when I passed the attached file (named "DS Not detected signedXML.xml.txt") to  this website ('https://validation.teda.th/webportal/#/validate), it could not detect the signature element in the file. 
However the website managed to detect signature element when another file generated by csdes4j with similar element(named " DS Detected signedXML.xml.txt")    Here's the code I am using for generate "DS Not detect signedXML.xml.txt". Thank you for your help. 

async function createEnvelopedSignature(keys, algorithm, signingXml, options) {
    const signedXml = new xadesjs.SignedXml();
    const hash = !(options && options.hash) ? "SHA-256" : options.hash;
   const signingOptions = {
        references: [
            { hash, transforms: ["enveloped"], uri: '' },
        ],
    };
    if (options) {
        if (options.certificate) {
            signingOptions.x509 = [options.certificate];
            signingOptions.signingCertificate = options.certificate;
            signingOptions.id = options.id
        }
        if (options.policy) {
            signingOptions.policy = options.policy;
        }
    }
const testSign1 = () => {
    var time = Date.now()
    const doc = fs.readFileSync("./ETDA-invoice.xml", { encoding: "utf8" });
    const signingXml = xadesjs.Parse(doc);

    getKeyP('private-0700040000000000-')
        .then(async (key) => {
            key.algorithm.hash.name = 'SHA-512'
            const algorithm = { name: "RSASSA-PKCS1-v1_5", hash: "SHA-512" };
            await createEnvelopedSignature(key, algorithm, signingXml, {
                id: `xmldsig-${time}`,
                hash: 'SHA-512',
                references: [{ hash: "SHA-512", transforms: ["enveloped"] }],
                certificate: "MIIGgTCCBGmgAwIBAgIUeaHFHm5f58zYv20JfspVJ3hossYwDQYJKoZIhvcNAQEFBQAwgZIxCzAJBgNVBAYTAk5MMSAwHgYDVQQKExdRdW9WYWRpcyBUcnVzdGxpbmsgQi5WLjEoMCYGA1UECxMfSXNzdWluZyBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTE3MDUGA1UEAxMuUXVvVmFkaXMgRVUgSXNzdWluZyBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eSBHMjAeFw0xMzEwMzAxMjI3MTFaFw0xNjEwMzAxMjI3MTFaMHoxCzAJBgNVBAYTAkJFMRAwDgYDVQQIEwdCcnVzc2VsMRIwEAYDVQQHEwlFdHRlcmJlZWsxHDAaBgNVBAoTE0V1cm9wZWFuIENvbW1pc3Npb24xFDASBgNVBAsTC0luZm9ybWF0aWNzMREwDwYDVQQDDAhFQ19ESUdJVDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJgkkqvJmZaknQC7c6H6LEr3dGtQ5IfOB3HAZZxOZbb8tdM1KMTO3sAifJC5HNFeIWd0727uZj+V5kBrUv36zEs+VxiN1yJBmcJznX4J2TCyPfLk2NRELGu65VwrK2Whp8cLLANc+6pQn/5wKh23ehZm21mLXcicZ8whksUGb/h8p6NDe1cElD6veNc9CwwK2QT0G0mQiEYchqjJkqyY8HEak8t+CbIC4Rrhyxh3HI1fCK0WKS9JjbPQFbvGmfpBZuLPYZYzP4UXIqfBVYctyodcSAnSfmy6tySMqpVSRhjRn4KP0EfHlq7Ec+H3nwuqxd0M4vTJlZm+XwYJBzEFzFsCAwEAAaOCAeQwggHgMFgGA1UdIARRME8wCAYGBACLMAECMEMGCisGAQQBvlgBgxAwNTAzBggrBgEFBQcCARYnaHR0cDovL3d3dy5xdW92YWRpc2dsb2JhbC5ubC9kb2N1bWVudGVuMCQGCCsGAQUFBwEDBBgwFjAKBggrBgEFBQcLAjAIBgYEAI5GAQEwdAYIKwYBBQUHAQEEaDBmMCoGCCsGAQUFBzABhh5odHRwOi8vb2NzcC5xdW92YWRpc2dsb2JhbC5jb20wOAYIKwYBBQUHMAKGLGh0dHA6Ly90cnVzdC5xdW92YWRpc2dsb2JhbC5jb20vcXZldWNhZzIuY3J0MEYGCiqGSIb3LwEBCQEEODA2AgEBhjFodHRwOi8vdHNhMDEucXVvdmFkaXNnbG9iYWwuY29tL1RTUy9IdHRwVHNwU2VydmVyMBMGCiqGSIb3LwEBCQIEBTADAgEBMA4GA1UdDwEB/wQEAwIGQDAfBgNVHSMEGDAWgBTg+A751LXyf0kjtsN5x6M1H4Z6iDA7BgNVHR8ENDAyMDCgLqAshipodHRwOi8vY3JsLnF1b3ZhZGlzZ2xvYmFsLmNvbS9xdmV1Y2FnMi5jcmwwHQYDVR0OBBYEFDc3hgIFJTDamDEeQczI7Lot4uaVMA0GCSqGSIb3DQEBBQUAA4ICAQAZ8EZ48RgPimWY6s4LjZf0M2MfVJmNh06Jzmf6fzwYtDtQLKzIDk8ZtosqYpNNBoZIFICMZguGRAP3kuxWvwANmrb5HqyCzXThZVPJTmKEzZNhsDtKu1almYBszqX1UV7IgZp+jBZ7FyXzXrXyF1tzXQxHGobDV3AEE8vdzEZtwDGpZJPnEPCBzifdY+lrrL2rDBjbv0VeildgOP1SIlL7dh1O9f0T6T4ioS6uSdMt6b/OWjqHadsSpKry0A6pqfOqJWAhDiueqgVB7vus6o6sSmfG4SW9EWW+BEZ510HjlQU/JL3PPmf+Xs8s00sm77LJ/T/1hMUuGp6TtDsJe+pPBpCYvpm6xu9GL20CsArFWUeQ2MSnE1jsrb00UniCKslcM63pU7I0VcnWMJQSNY28OmnFESPK6s6zqoN0ZMLhwCVnahi6pouBwTb10M9/Anla9xOT42qxiLr14S2lHy18aLiBSQ4zJKNLqKvIrkjewSfW+00VLBYbPTmtrHpZUWiCGiRS2SviuEmPVbdWvsBUaq7OMLIfBD4nin1FlmYnaG9TVmWkwVYDsFmQepwPDqjPs4efAxzkgUFHWn0gQFbqxRocKrCsOvCDHOHORA97UWcThmgvr0Jl7ipvP4Px//tRp08blfy4GMzYls5WF8f6JaMrNGmpfPasd9NbpBNp7A=="
            });
            fs.writeFileSync("./signed.xml", xmlCore.Stringify(signingXml), { flag: 'w' });
        })
    console.log('done ', time)
}

[DS Detected signedXML.xml.txt](https://github.com/PeculiarVentures/xadesjs/files/5331566/DS.Detected.signedXML.xml.txt)

[DS Not detected signedXML.xml.txt](https://github.com/PeculiarVentures/xadesjs/files/5331568/DS.Not.detected.signedXML.xml.txt)

**Comment by chronorus** [comment]
Hi, Please ignore my previous files. The following files should be more obvious. The newly attached files came from the same program. The signature element in "signedXML.xml.txt" could not be detected but the other one got reformmated then the website managed to detect the signature element. Sorry for the trouble. 

[signedXML.xml.txt](https://github.com/PeculiarVentures/xadesjs/files/5331674/signedXML.xml.txt)
[signedXML formatted.xml.txt](https://github.com/PeculiarVentures/xadesjs/files/5331675/signedXML.formatted.xml.txt)

**Comment by chronorus** [comment]
.

**Comment by rmhrisk** [comment]
So issue is resolved?

**Comment by chronorus** [comment]
> So issue is resolved?
Not really, the signed XML passed several other validation tools. It's probably best to revisit this issue after new info acquired. 
Your team's contribution is truly admired.
