### ISSUE TITLE
how to add custom attributes to the signature node?

### ISSUE THREAD

**Issue by bjrmatos** [PeculiarVentures/xadesjs#14]
congrats for the release!

a minor question.. in `xml-crypto` i can specify custom attribute for the resulting `<Signature />`

example in `xml-crypto`:

```js
signGenerator.computeSignature(xmlStr, {
    prefix: 'ds',
    attrs: {
      Id: 'customIdPerSignatureInMyApplication'
    },
    // .. other options here ..
  });
```

result -> `<Signature Id="customIdPerSignatureInMyApplication"> <!-- signature content here --></Signature>`, 

how this can be done in `xadesjs`?

**Comment by rmhrisk** [comment]
You can set the id on the Signature -
https://github.com/PeculiarVentures/xadesjs/blob/master/src/signature.ts#L20-L29

And SignedInfo -
https://github.com/PeculiarVentures/xadesjs/blob/master/src/signed_info.ts#L53-L62

**Comment by bjrmatos** [comment]
clear! 👌
