### ISSUE TITLE
how to add custom KeyInfo clause?

### ISSUE THREAD

**Issue by bjrmatos** [PeculiarVentures/xadesjs#15]
in `xml-crypto` i can add a custom [KeyInfo implementation](https://github.com/yaronn/xml-crypto#filekeyinfo) to customize the output and it seems like in `xadesjs` it is supported too -> `signedXml.KeyInfo.AddClause(keyInfoClause);` is that correct? if so, do you have some guide how the implementation would look like?

**Comment by rmhrisk** [comment]
Yes, the API is modeled off of .NET so it would look something like:

```
        KeyInfo keyInfo = new KeyInfo();
        keyInfo.AddClause(new CustomKeyInfoValue();	
        signedXml.KeyInfo = keyInfo;
```

Maybe @microshine can provide something more specific.

**Comment by rmhrisk** [comment]
BTW @bjrmatos it would be awesome if you could help with us building samples and documentation, these are great questions. Our hope is we can evolve the inline JSDOC documentation and build documentation based on that - https://github.com/PeculiarVentures/xadesjs/issues/7.

Any help you can offer would be appriciated.

**Comment by bjrmatos** [comment]
@rmhrisk yes, i can do that.. let me try `xadesjs` a bit more to feel more confortable with the API, i'm planning to try `xadesjs` in some apps that use XML DSIG at work, so lets see how it goes!

**Comment by rmhrisk** [comment]
That is awesome.

**Comment by rmhrisk** [comment]
Closing as it seems resolved.
