### ISSUE TITLE
Should we specify our xmldom as dependency

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/xadesjs#20]
@microshine  in this commit: https://github.com/PeculiarVentures/xadesjs/commit/04e5101697ec431153f314056c16c56264f56997

You make use need to provide this package on their own, would it be better to specify our private copy as a dependency?

```
"git+ssh://github.com/PeculiarVentures/xmldom"
```

**Comment by bjrmatos** [comment]
yes! and export it (at least until your PRs are merged), it'll work with just `"xmldom": "PeculiarVentures/xmldom"`
