### ISSUE TITLE
Readme node example outdated or not tested?

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [PeculiarVentures/xadesjs#31]
I'm not sure at all how to use this package, the examples seem to be incorrect in the readme.
I ran 
npm install xadesjs --save

to install the package.  (there are no install instructions in the readme, I hope this is all that's required)

According to the readme the example code should just work since it doesn't say you need to separately install anything else, however the example code is a fail:

First line:
`var xadesjs = require("xades");`
Error: Cannot find module 'xades'
    at Function.Module._resolveFilename (module.js:325:15)

I think this is probably a typo and should be xadesjs?  I assumed so and changed it 

```
var xadesjs = require("xadesjs");
var DOMParser = require("xmldom").DOMParser;
```

and then I get this:
Error: Cannot find module 'xmldom'
    at Function.Module._resolveFilename (module.js:325:15)

But when I check under xadesjs in modules it contains xmldom in it's node_modules!?

And that's as far as I'm willing to waste time on this.

Is the example code just completely wrong and needs to be re-written or ....

**Comment by rmhrisk** [comment]
Sample was edited after it was tested and not retested and bug was introduced (by me), just tried here is what I did:

```
git clone https://github.com/PeculiarVentures/xadesjs.git
cd xadesjs
npm install
```

I then copied the first sign sample to "test.js", I made sure the package reference include the path to the file (./built/xades.js) and then ran the sample and it worked.

Ryan

**Comment by WhatFreshHellIsThis** [comment]
Just to be clear I was talking about the sample code on the readme page which I see has been changed but certainly still will not work as a standalone sample snippet.
It's my expectation that a sample of code in a readme should work but I understand you are using it for illustration purposes and expect people to clone the repo to try samples so I guess it's just a difference of opinion, thank you for looking into it though.  I've since figured out what is amiss and I'm sure others will as well given enough time.

**Comment by rmhrisk** [comment]
I copied the sample from the from the readme ant put it in a file called test.js and ran it after I did the above and it worked for me, you will need to give me more to work with.

**Comment by WhatFreshHellIsThis** [comment]
Perhaps I was caught between updates at your end or something?

Aside from the typo in the original example where it was including "xades" and not "xadesjs" which was easily fixed it was throwing an exception for missing XmlDom which actually *is* in the package.json included in my install from this morning (not sure why it wasn't picked up by Node) but I had to install xmldom myself into my project to get it to work.  

If you have tried it since your updates on a clean system from npm install xadesjs and it worked then I guess this issue is closed and I was just suffering from bad timing or something.

**Comment by WhatFreshHellIsThis** [comment]
ok, also other issues with sample, these are the first lines of the sample code in the readme:

var xadesjs = require("./built/xades.js");
var DOMParser = require("xmldom").DOMParser;
var XMLSerializer = require("xmldom").XMLSerializer;
var WebCrypto = require("node-webcrypto-ossl").default;

Aside from the separately reported issue that webCrypto is not installing, xmldom is a module under your module and not exposed by it as far as I can tell so that example code will fail until xmldom is installed manually (and node-webcrypto-ossl since it will be the same issue even if you get it to install for your module) before users can run the sample code.

I know this is probably obvious to many people and I understand if you want to leave it out but I highly recommend it for relative newbies to node like myself or perhaps there is some way to expose those required modules to the user so they don't have to redundantly install them again in their own project.

**Comment by rmhrisk** [comment]
The only thing I changed based on my git pull was to name the location and real file name of the dependency in the samples located in the README.md:

```
var xadesjs = require("./built/xades.js");
```

I did not publish a new npm, or test npm based installation.

As for the XMLDOM issue, I think I know what happened. There is a bug in XMLDOM that has not been fixed in the [main release](https://github.com/jindw/xmldom/issues/166). The author of that package created a new one called xmldom-alpha and that is what the [package is referring to](https://github.com/PeculiarVentures/xadesjs/blob/master/package.json#L31) but the samples refer to the regular xmldom, which is not installed by npm. It seems my machine was not totally clean as I had the xmldom package installed globally.

I guess until he publishes a new XMLDOM with the fix the readme should also refer to xmldom-alpha.

I also did not have any issues with WebCrypto not installing, I will look and comment on your other issue on this topic.

With the above exceptions things work for me, if they are not working for you please let me know.

**Comment by rmhrisk** [comment]
Closing as I think, based on the above you are working (but please re-open if you are still having issues).

**Comment by WhatFreshHellIsThis** [comment]
I got it to work so it's ok for me but others will still have this same issue; I suggest it would be good for the users to know how to get the example working (i.e. required to install xmldom and node-webcrypto-ossl before the sample code can be run for) so maybe mention how to install and use in the readme?

**Comment by rmhrisk** [comment]
Unfortunately, npm picks up the readme from the git repository dynamically, it does not use a snapshot of the readme at the time of publication.

This is the root of your issues really, the README in the repository is for the release in the repository and not for the release in NPM, it is accurate for what is in the repo right now.

I will update the npm release in a week or two.

Ryan
