### ISSUE TITLE
http://www.w3.org/TR/2001/REC-xml-c14n-20010315

### ISSUE THREAD

**Issue by ponyesteves** [PeculiarVentures/xadesjs#33]
Hi, @rmhrisk @microshine! I'm having some trouble validating signatures canonicalize by xml-c14n using xml-crypto lib. I know you build on top of it and added some features, among other c14n support. So maybe I could use you're help
I have this signature and i can't validate it. I'm sure the dif is in the canonicalization method

 
```xml
<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
<SignedInfo>
  <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
  <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
  <Reference URI="">
    <Transforms>
      <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
      <Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
    </Transforms>
    <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
    <DigestValue>txO/Q5rCzp2FMT3FgOQfVzwCcFk=</DigestValue>
  </Reference>
</SignedInfo>
    <SignatureValue>wpnU9yX9RDxQsMYPAdiqR14EObYvsboXgXFatyPC7g3rcgSIT5VQdAdgKtUeKMpXi0hWDK/wyIsp53E0Jl9T46ooLFDZMuTYs7UAyiXX/MsvPGCYCmRK7uf0Cv3Wuu6bSCyzBgjQQ/sP130nYUGEXG9w4TxT7BAyanYhS4Fxl5A=</SignatureValue><KeyInfo><X509Data><X509IssuerSerial><X509IssuerName>CN=Correo Uruguayo - CA, OU=SERVICIOS ELECTRONICOS, O=ADMINISTRACION NACIONAL DE CORREOS, C=UY</X509IssuerName><X509SerialNumber>155761856642617054135126896023459966393</X509SerialNumber></X509IssuerSerial></X509Data></KeyInfo></Signature>
```

__I can' t verify this signature! I think it have something to do with the canonicalization process. The cannonXml (excC14N) would be:__

```xml 
<SignedInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
  <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"></CanonicalizationMethod>
  <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"></SignatureMethod>
  <Reference URI="">
    <Transforms>
      <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"></Transform>
      <Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"></Transform>
    </Transforms>
    <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"></DigestMethod>
    <DigestValue>txO/Q5rCzp2FMT3FgOQfVzwCcFk=</DigestValue>
  </Reference>
</SignedInfo>
```
Would c14N cannon be the same? 

Thanks for any data, advice you could offer me

**Comment by rmhrisk** [comment]
@ponyesteves would love to help but we had to re-write all of that to get things to work well. We took inspiration from xml-crypto on how to approach certain aspects of using XML in browser. 

In the end, we ended up being more of a port of the mono xmldsig than xml-crypto. We would be happy to try to help you with xadesjs if you can give us a repro.

**Comment by mendesf** [comment]
Hey @ponyesteves, have you got any progress? I have had the same issue.

**Comment by microshine** [comment]
@mendesf @ponyesteves Have you tried to check your xml signature with `xadesjs`?
https://github.com/PeculiarVentures/xadesjs#check-xades-bes-signature
