### ISSUE TITLE
Add coveralls 

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/xadesjs#38]
https://coveralls.io

**Comment by rmhrisk** [comment]
@hildjj I have added coveralls to this project (though I should have used a pull request vs editing master).

You can see the tests running here : https://travis-ci.org/PeculiarVentures/xadesjs/jobs/156967336.

It seems that the results are not making it to the coveralls website, do you have any ideas why?

**Comment by hildjj** [comment]
Looks like you're missing the `after_success` bit.

**Comment by rmhrisk** [comment]
Thanks @hildjj your a gentleman and a scholar.
