### ISSUE TITLE
Update to PKIjs-es6

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/xadesjs#43]

**Comment by rmhrisk** [comment]
Fixed

**Comment by YuryStrozhevsky** [comment]
I can see only PKIjs v1 code in master and development version of XAdESjs. Is there any other version of the code?

**Comment by rmhrisk** [comment]
@microshine can you confirm? I understood the development branch had moved to the es6 version.

**Comment by microshine** [comment]
Closed #46
