### ISSUE TITLE
xadesjs.com demo not work at mobile browsers

### ISSUE THREAD

**Issue by kjur** [PeculiarVentures/xadesjs#44]
Hi.

xadesjs.com demo page seems not to work on mobile browsers such like mobile chrome, mobile firefox and mobile safari. Can you provide supported browser list for it?

Thanks.

**Comment by rmhrisk** [comment]
We had a regression recently, once we finish up with some test coverage improvements to the webcrypto polyfill a (in the next few days) we will come back and fix this issue.

**Comment by rmhrisk** [comment]
Adding @microshine

**Comment by kjur** [comment]
Thank you for your quick reply :)

**Comment by rmhrisk** [comment]
Fixed
