### ISSUE TITLE
Multiple signers - how to?

### ISSUE THREAD

**Issue by george-i** [PeculiarVentures/xadesjs#49]
I'm new to electronic signature and I'm interested on xadesjs.

I need an advice, or strategy recommendation.
Some documents require to be signed by two or more users. Maybe thousands.
What would be the right way to do this?
Perhaps I should generate a PDF file for up to 20 users and embed each user's signature in the same file?

**Comment by rmhrisk** [comment]
@george-i which format to use depends on your use case.

A XML document, one to be read by a machine, would probably make sense to sign with xadesjs/xmldsigjs.

If it is a human readable document, like a contract, then a PDF is probably more interesting.

You can have multiple people sign either format.

**Comment by george-i** [comment]
Does xadesjs support PDF? 

My concern about multiple signers is that the PDF file may grow too much.

This is an example of scenario:
- an user fills a html form;
- the server generates a PDF file;
- then one or more users view the PDF file and eventually sign it.

These PDF files should have a page with a text, followed by pages with the list of signers, containing identification information  (address, ID, phone, etc) and a representation of a handwritten signature.
This PDF file may be then sent to different institutions, so it must have a legal value.

I'm trying to find someone or a software to accomplish these requirements and I'm open to paid options as well.

**Comment by rmhrisk** [comment]
@george-i Re: size anything XML will be larger than something ASN.1 but it shouldnt be deal a hughe difference.

Can you sign a PDF with XADESjs? Sure, XADESjs would be a "detached" signature, hash the document and sign that hash.

But to me it sounds like what you really want os a document signing solution for people to sign, if thats the case I would do a PDF file signed with a PAdES signature. This is what Acrobat does.

Email me at ryan@peculiarventures.com, I have something to show you.
