### ISSUE TITLE
Signing multiple documents

### ISSUE THREAD

**Issue by peterbartels** [PeculiarVentures/xadesjs#51]
I want to sign multiple documents with multiple reference ids which should be possible according to the standard. I cannot find an example on the docs page. Does the library support it?

**Comment by rmhrisk** [comment]
Yes, you can build such a signature with xadesjs, we, unfortunately, don't have many examples at this time.

Maybe @microshine can explain at a high level how to do.

**Comment by microshine** [comment]
@peterbartels `xadesjs` API supports multiple reference. Here is type declaration for `Sign` method options.

Example for multiple reference signing ([source code](https://github.com/PeculiarVentures/xadesjs/blob/master/examples/html/src/main.js#L99))
```javascript
signature = new XAdES.SignedXml();

return signature.Sign(                    // Signing document
   {name: "RSASSA-PKCS1-v1_5", hash: "SHA-256"},    // algorithm 
    keys.privateKey,                        // key 
    XAdES.Parse(`<root><child id="id-1">Simple xml</child><child id="id-2">Simple xml #2</child></root>`),                  // document
    {                                       // options
        keyValue: keys.publicKey,
        references: [
            { id: "id-1", hash: "SHA-256", transforms: transforms },
            { id: "id-2", hash: "SHA-512", transforms: transforms },
        ],
        signerRole: { claimed: ["BOSS"] }
    });
```
