### ISSUE TITLE
Specify transforms when verifying?

### ISSUE THREAD

**Issue by mbrevda** [PeculiarVentures/xadesjs#53]
My xml has the following under `Reference`:

```xml
<Transforms>
    <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
</Transforms>
```

And I fail verification every time. I was wondering if this transform might be something that I would have to set/pass before verifying?

**Comment by microshine** [comment]
@mbrevda Could you share your xml for debugging?

**Comment by mbrevda** [comment]
Sure - can I send it to you directly somehow?

**Comment by microshine** [comment]
You can send it to my email microshine@mail.ru

**Comment by microshine** [comment]
This is error in `xmldsigjs`. I create new issue for it https://github.com/PeculiarVentures/xmldsigjs/issues/11

**Comment by microshine** [comment]
@mbrevda I published new version of `xmldsigjs` v2.0.10
Could you check if it it works for your xml files?

**Comment by mbrevda** [comment]
whoa! Awesome, this work great now! Thanks so much!

As a side question: does the api expose any way to get more info about the signature? Like who signed it, time it was signed or other cert info? Also, is there an api to extract the data or do I need to parse the xml on my own for that?

**Comment by microshine** [comment]
There are [xades.d.ts](https://github.com/PeculiarVentures/xadesjs/blob/master/index.d.ts) and [xmldsig.d.ts](https://github.com/PeculiarVentures/xmldsigjs/blob/master/index.d.ts). They describe lib API.

[Here](https://github.com/PeculiarVentures/xadesjs/blob/gh-pages/index.html#L133-L182) is example of SignedInfo data printing.

I'm not sure there is a simple way to extract signed content. I'll check it a bit later

**Comment by microshine** [comment]
You can use d.ts files in your project. They help to check data and shows lib API.

I use it in [Visual Studio Code](https://code.visualstudio.com/). I think the others IDE can use it too

![image](https://user-images.githubusercontent.com/7333669/31510105-656e5ac0-af8c-11e7-9c26-c7919d18b1fe.png)
