### ISSUE TITLE
Question: How to limit SigningTime precision?

### ISSUE THREAD

**Issue by alexey-pelykh** [PeculiarVentures/xadesjs#59]
@microshine if to create a PR, would it be better to specify SigningTime format? In my case, milliseconds are not needed, yet that's problem of recipient software, yet somehow I need to remove them from SigningTime. How it would be better to specify formatting for that date-time?

**Comment by microshine** [comment]
@alexey-pelykh [SigningTime](https://github.com/PeculiarVentures/xadesjs/blob/master/src/xml/signed_signature_properties.ts#L41) is a property of [SignedSignatureProperties](https://github.com/PeculiarVentures/xadesjs/blob/master/src/xml/signed_signature_properties.ts#L30) which uses [XmlDateTimeConverter](https://github.com/PeculiarVentures/xadesjs/blob/master/src/xml/converter.ts#L3)

```ts
@XmlChildElement({
    localName: XmlXades.ElementNames.SigningTime,
    namespaceURI: XmlXades.NamespaceURI,
    prefix: XmlXades.DefaultPrefix,
     converter: XmlDateTimeConverter,
})
public SigningTime: Date;
```

Current version doesn't support custom serialization for this property. To support different formats you have to create new class for SigningTime which extends XadesObject and overrides `OnGetXml` and `OnLoadXml` methods

[object_identifier.ts](https://github.com/PeculiarVentures/xadesjs/blob/master/src/xml/object_identifier.ts) has custom implementation

**Comment by microshine** [comment]
I've got an idea

- add [dateformat](https://www.npmjs.com/package/dateformat) module

```ts
@XmlElement({
    localName: XmlXades.ElementNames.SigningTime,
})
export class SigningTime extends XadesObject {

    @XmlContent({
        defaultValue: new Date(),
        required: true,
    })
    public Value: Date;

    // date format string (ISO by default)
    public Format: string;

    protected OnLoadXml(e: Element) {
         // parse element's text content
    }

    protected OnGetXml(e: Element) {
        // convert Valuer to string and add to element's content
    }

}
```

@alexey-pelykh What do you think about it?

**Comment by alexey-pelykh** [comment]
@microshine sounds great! Or even formatter callback

**Comment by microshine** [comment]
Could you show example of cb usage for SignigTime?
If we can apply EventEmitter we should do it on xml-core layer.

**Comment by alexey-pelykh** [comment]
Well, I don't really think it should go _that_ deep, since it's XAdES-specific, due to the variety of implementations, workarounds should be somewhere there. What I meant is
```
signingTime.Value = new Date();
signingTime.Format = "YYYY-MM-DD"
// or
signingTime.Format = (date) => moment(date).format()
```

**Comment by microshine** [comment]
it looks ok.

But we should use xsd:datetime spe

**Comment by alexey-pelykh** [comment]
true! `xsd:datetime` specifies options, e.g. according to spec, milliseconds are not required, and in my case - not needed, so how to achieve that? :)

**Comment by microshine** [comment]
We should add SigningTime class. It can use multi type Filter property if needed (I don't like multi type properties). Could make PR?

**Comment by alexey-pelykh** [comment]
Filter or Format?

**Comment by microshine** [comment]
I like `signingTime.Format = "YYYY-MM-DD"`. I think it must resolve all cases and easy to use

**Comment by alexey-pelykh** [comment]
alternatively, we can move that to options?

**Comment by microshine** [comment]
ok

**Comment by alexey-pelykh** [comment]
@microshine https://www.npmjs.com/package/dateformat vs https://www.npmjs.com/package/moment - your choice is dateformat?

**Comment by rmhrisk** [comment]
We use moment in many of our projects. But dateformat looks much smaller.

**Comment by alexey-pelykh** [comment]
Same story here, we use moment a lot, yet not tried dateformat. Anyhow, choice is yours to make

**Comment by rmhrisk** [comment]
I would say in this case dateformat() is probably the better choice.

**Comment by alexey-pelykh** [comment]
I've hit into https://github.com/rollup/rollup-plugin-typescript/issues/68 (with dateformat), which goes a little bit beyond my TS knowledge

**Comment by rmhrisk** [comment]
@microshine is mr TS.

**Comment by microshine** [comment]
![image](https://user-images.githubusercontent.com/7333669/33366620-d7eda728-d4fc-11e7-86c0-ddd12bd11202.png)

**Comment by alexey-pelykh** [comment]
```

**Comment by alexey-pelykh** [comment]
@microshine ^

**Comment by microshine** [comment]
Did you install `@types/dateformat`?

**Comment by alexey-pelykh** [comment]
```
"dependencies": {
    "@types/dateformat": "^1.0.1",
    "dateformat": "^3.0.2"
  },
```

**Comment by microshine** [comment]
I've got the same error for xadesjs. I'm trying to resolve it

**Comment by microshine** [comment]
I fixed it by
```ts
const dateFormat = require("dateformat") as DateFormatStatic;
```

**Comment by alexey-pelykh** [comment]
fine with me, as long as it doesn't break anything for you, since it's quite an odd construction

**Comment by microshine** [comment]
TS supports `require`. It returns type `any`. This is why I used type casting via `require("dateformat") as DateFormatStatic`

**Comment by alexey-pelykh** [comment]
Not sure if proper yet https://github.com/PeculiarVentures/xadesjs/pull/60
