### ISSUE TITLE
XPATH Transform

### ISSUE THREAD

**Issue by pemedina** [PeculiarVentures/xadesjs#67]
Hello,

My xml requires this transformer:

```
<ds:Transform Algorithm="http://www.w3.org/TR/1999/REC-xpath-19991116">
        <ds:XPath>not(ancestor-or-self::ds:Signature)</ds:XPath>
 </ds:Transform>
```

Roughly translated from documentation:

**_Requires an  enveloped reference to the whole certifcation with URI="". This reference shall contain a XPATH transformation (algoritmo http://www.w3.org/TR/1999/REC-xpath-19991116): not(ancestor-or-self::ds:Signature)_**

¿Is this supported / implemented?

**Comment by rmhrisk** [comment]
xadsjs is based on xmldisgjs, it uses xml-code, which uses xpath.js.

XPATH should work, some transforms are more complicated than others but I expect it will be fine but without samples it is impossible to say.

**Comment by pemedina** [comment]
Thanks for your reply. 
Please let me know what kind of samples are you looking for? I have the xml to sign, and the signed xml generated using java. Is this what you need?

**Comment by microshine** [comment]
It's possible to add and use new transform. You just need to extend [Transform](https://github.com/PeculiarVentures/xmldsigjs/blob/master/src/xml/transform.ts) class from `xmldsigjs` and implement `GetOutput` method. [Here](https://github.com/PeculiarVentures/xmldsigjs/tree/master/src/xml/transforms) are `xmldsigjs` transforms which you can use like example.

But there is no way to add new Transform to `Sign` method options. You need to do it [programmatically](https://github.com/PeculiarVentures/xmldsigjs/blob/master/src/signed_xml.ts#L545) like I do it in [ApplySignOptions](https://github.com/PeculiarVentures/xmldsigjs/blob/master/src/signed_xml.ts#L490) protected method.

**Comment by pemedina** [comment]
Thanks to both of you.
Checking now the links provided.
