### ISSUE TITLE
Validate with Java XmlSignature

### ISSUE THREAD

**Issue by ebuyuk** [PeculiarVentures/xadesjs#79]
Hello,
I want to sign at mobile device and send to server signed xml data. Could I validate in my server with XmlSignature Java ?

Thank you all

**Comment by rmhrisk** [comment]
Yes.

**Comment by ebuyuk** [comment]
Could you give a simple code snippet.

**Comment by rmhrisk** [comment]
You want a sample for how to do XMLDSIG sample in Java?

**Comment by rmhrisk** [comment]
Here is such a sample: https://www.programcreek.com/java-api-examples/?class=javax.xml.crypto.dsig.XMLSignature&method=validate
