### ISSUE TITLE
How to make the DigestMethod algorithm not take default value DefaultDigestMethod?

### ISSUE THREAD

**Issue by Jairos2015** [PeculiarVentures/xadesjs#83]
How to make the DigestMethod algorithm not take default value DefaultDigestMethod = "http://www.w3.org/2001/04/xmlenc#sha256" but "http://www.w3.org/2001/04 / xmldsig-more # rsa-sha256 "?.

In xmldsigjs XmlSignature sets DefaultDigestMethod: "http://www.w3.org/2001/04/xmlenc#sha256" 
and then uses it as the default value for the DigestMethod. 
I have changed the values ​​xadesXml.XmlSignature.DefaultDigestMethod =
                                    "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256";
and then xadesXml.XmlSignature.DigestMethod =
                                    "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"; for ds: SignedInfo. It's OK.

But use
const getReference = signature.GetXml ().getElementsByTagName (`ds: Reference`);
                                  if (getReference.length) {
                                    console.log (getReference.length);
                                    getReference [0] .setAttribute ( "URI", `# $ {cufe} -KeyInfo` );
                                    getReference [0] .DigestMethod = "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256";

for DigestMethod of KeyInfo or for signedprops:

getReference [2] .setAttribute ("URI", `#xmldsig - $ {cufe} -signedprops` );
getReference [2] .DigestMethod ="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256";

This does not work. 
Leave the default value in the xml document. I appreciate your help

**Comment by microshine** [comment]
I've published the new version of `xmldsigjs` v2.0.24. There was a problem with constants exporting.

The given example sets custom algorithms for signed XML.
- SignatureMethod:  rsa-sha512
- Reference#KeyInfo001: sha1
- Reference: sha384
- Reference#SignedProperties001: sha512

`XAdESjs` uses the hash algorithm from the SigningAlgorithm ([source](https://github.com/PeculiarVentures/xadesjs/blob/master/src/signed_xml.ts#L169)). If you want to use another hash algorithm we need to update module and extend options for the Sign method (PR is appreciated).

### TS example
```ts
import { Crypto } from "@peculiar/webcrypto";
import * as xades from "xadesjs";
import * as xmldsig from "xmldsigjs";

async function main() {
  const crypto = new Crypto();

  // Set crypto engine for XAdES
  xades.Application.setEngine("NodeJS", crypto);

  // Generate RSA keys
  const algorithm = {
    name: "RSASSA-PKCS1-v1_5",
    hash: "SHA-512",
    publicExponent: new Uint8Array([1, 0, 1]),
    modulusLength: 2048,
  };
  const keys = await crypto.subtle.generateKey(algorithm, false, ["sign", "verify"]);

  // Sign XML
  const xmlDoc = xades.Parse(`<root><child attr="Some"/></root>`);
  const signedXml = new xades.SignedXml();

  // Set Id for KeyInfo
  signedXml.XmlSignature.KeyInfo.Id = "KeyInfo001";
  
  // Set Id for SignedProperties
  signedXml.SignedProperties.Id = "SignedProperties001";

  // Create Reference for KeyInfo
  const keyInfoRef = new xmldsig.Reference("#KeyInfo001");
  keyInfoRef.DigestMethod.Algorithm = xmldsig.SHA1_NAMESPACE;

  // Add Reference to SignedInfo
  signedXml.XmlSignature.SignedInfo.References.Add(keyInfoRef);

  const signature = await signedXml.Sign(
    algorithm,                              // algorithm
    keys.privateKey,                        // key
    xmlDoc,                                 // document
    {                                       // options
      keyValue: keys.publicKey,
      id: "Signature001",
      references: [
        { hash: "SHA-384", transforms: ["enveloped"] }
      ],
      productionPlace: {
        country: "Country",
        state: "State",
        city: "City",
        code: "Code",
      },
      signingTime: {
        format: "isoDateTime"
      }
    });

  console.log(signature.toString());
}

main()
  .catch(e => console.error(e));
```

### XML
```xml
<ds:Signature Id="Signature001"
    xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
    <ds:SignedInfo>
        <ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
        <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha512"/>
        <ds:Reference URI="#KeyInfo001">
            <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
            <ds:DigestValue>khKo91XCbUrbzjmP2HQbi+M8rIM=</ds:DigestValue>
        </ds:Reference>
        <ds:Reference>
            <ds:Transforms>
                <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
            </ds:Transforms>
            <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#sha384"/>
            <ds:DigestValue>HzlZkV6sYvp1TLQJYznq5bHTHM3sQlwQbzCSiETl6BWfY0uqOS/S3ihjOM3xQRlf</ds:DigestValue>
        </ds:Reference>
        <ds:Reference URI="#SignedProperties001" Type="http://uri.etsi.org/01903#SignedProperties">
            <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha512"/>
            <ds:DigestValue>prMjWI6i6kfXrtDv5Meex7xSmY1mKC3vperY77Pc8Evs2+ZcmJ/ZoU8kUrRj1Zk+/p5xOUZY1uVolISoMlz7Tg==</ds:DigestValue>
        </ds:Reference>
    </ds:SignedInfo>
    <ds:SignatureValue>nFlA4SNBPWNwAOtOaibD8jo/LYS21UC/417zCwKveAm9IaaPpj5Zar3r9Oc8udOqUH0SavovShaW1vQ36D3++HEtNSZStVLSISzNmqMGRnePJ/8AFkilT9NrTZLRdwwh0Jpv6P4o3tetUvvGbRqkcRxsgfvQsa3h4jkEsqWQje8tL6yRUmVN3A+zRObOROxdfT9aaebYScwWnUcqTNtAD6wVjv3vP/PCA9btNg4wnjlO1NOJUgV0kiFksi45vVR3nefDoB4BD4AYbvOvXAPnp0ujEPCvhyAwAppzCrZoLaY78gx2wJFnuBk8aLwW8gDzrKrLO4ufwC8LkF7Hb0d+zQ==</ds:SignatureValue>
    <ds:KeyInfo Id="KeyInfo001">
        <ds:KeyValue>
            <ds:RSAKeyValue>
                <ds:Modulus>6H6SsowOibXSWYnCuOHG9xmKBXcJE0qBuZBHaFvAPHeQaqxwIRVQ/muk+tSTDBkdW6GONdp8efIhp02g22Hd+qj0UHtoL0MHwBNjqfNFErEzpcTn99TjCEffHbv1M25FF5rHndFhgm3FNgd5W7PjIjriFcGHT3hcep8VL7XcvGI5LbU2iHRchUOB/s5shbISJGiEithtTY32vKEWFYKjrFItjLhTKhEEaEtdIHCfnZuWk5PFkqXVcxO7fviTGyx/QaSdjgHgFSTDotqZghFLJit6253uDYczr0nLLsTQPaSvoYrhmKO0h8fXlsIlmjVyKR1JjlAQIIHswxyUk0MTqw==</ds:Modulus>
                <ds:Exponent>AQAB</ds:Exponent>
            </ds:RSAKeyValue>
        </ds:KeyValue>
    </ds:KeyInfo>
    <ds:Object>
        <xades:QualifyingProperties Target="#id-43fb817408a0"
            xmlns:xades="http://uri.etsi.org/01903/v1.3.2#">
            <xades:SignedProperties Id="SignedProperties001">
                <xades:SignedSignatureProperties>
                    <xades:SigningTime>2019-05-05T10:59:58+0300</xades:SigningTime>
                    <xades:SignatureProductionPlace>
                        <xades:City>City</xades:City>
                        <xades:StateOrProvince>State</xades:StateOrProvince>
                        <xades:PostalCode>Code</xades:PostalCode>
                        <xades:CountryName>Country</xades:CountryName>
                    </xades:SignatureProductionPlace>
                </xades:SignedSignatureProperties>
            </xades:SignedProperties>
        </xades:QualifyingProperties>
    </ds:Object>
</ds:Signature>
```

**Comment by Jairos2015** [comment]
Thank you for your answer. 

The algorithm reported in the Reference DigestMethod (KeyInfo, Completed Document, SignedProps) must be 
http://www.w3.org/2001/04/xmldsig-more#rsa-sha256 or 
http://www.w3.org/2001/04/xmldsig-more#rsa-sha384 or 
http://www.w3.org/2001/04/xmldsig-more#rsa-sha512.

Please, what is PR?

**Comment by rmhrisk** [comment]
A PR is a "pull request" - see https://yangsu.github.io/pull-request-tutorial/.

Right now the library matches the hash algorithm used from the SigningAlgorithm when setting SignedProperties (see https://github.com/PeculiarVentures/xadesjs/blob/master/src/signed_xml.ts#L169).

If you want to specify a different algorithm this will need to be changed, we do not know when we would be able to make that change but if you were to propose code changes to enable that we would consider accepting them into the project.

**Comment by rmhrisk** [comment]
One more note, the current behavior being discussed of XADESjs has been tested with https://www.aleksey.com/xmlsec/,  .NET's XMLDSIG and others so we think it is the correct behavior as it is interoperable.

If the current default behvior is not correct and changing it doesn't break interoperability we would consider changing it.

Based on what we are understanding from your post is you want to keep the default behavior but override the uri in the metadata so you can work with a non-conforming implementation.

This seems reasonable if that's the case, we just can't commit to adding this capability at this time but would be open to accepting a change if you were to do the work.

**Comment by Jairos2015** [comment]
Thanks for your reply. I am deepening more about my need and reviewing if what you offer is assimilated to them. This is my first big project with node.js and, if you can, I would ask you to wait a few days to take the relevant actions. Thanks again for your attention.

**Comment by Jairos2015** [comment]
I believe that I misinterpreted the directives of DIAN Colombia and when reviewing examples, they agree with what you stated. I consider closing this issue. Thank you and excuse me, please.
