### ISSUE TITLE
Problems making it work with typescript + webpack.

### ISSUE THREAD

**Issue by blaskurain** [PeculiarVentures/xadesjs#99]
The following test program compiles ok but the call to ```setEngine``` fails because ```xades.Application``` is undefined.

```typescript
import * as xades from 'xadesjs';

function main() {
    console.log("main BEGIN");
    xades.Application.setEngine("Browser", new Crypto());
}

main();
```
Webpack does include the ```xadesjs/build/xades.js``` file in the bundle but nothing gets exported from it.

Also, before that I got a ```ReferenceError: regeneratorRuntime is not defined``` error which I managed to fix by including ```regenerator-runtime/runtime.js``` as an entry point in webpack.

I attach a zip file with a minimal project (including the tentative fix for ```ReferenceError: regeneratorRuntime is not defined```) to reproduce the error if needed: [webpack-xades-test.zip](https://github.com/PeculiarVentures/xadesjs/files/4475421/webpack-xades-test.zip).

**Comment by donskov** [comment]
@blaskurain Hi. Please try to use https://github.com/babel/babel/issues/8829#issuecomment-456524916

**Comment by blaskurain** [comment]
Using Babel ```xades.Application``` is still undefined.

If I comment out the line ```exclude: /(node_modules|bower_components)/,``` from the webpack config babel emits this warning which is consistent with the runtime error reported initially:
```
WARNING in ./src/index.ts 5:2-19
"export 'Application' (imported as 'xades') was not found in 'xadesjs'
 @ multi ./src/index.ts
```
I guess my question is: how should I configure webpack/babel so that xadesjs exports the ```Application``` and the rest of of the types/values?

[webpack-xades-test.zip](https://github.com/PeculiarVentures/xadesjs/files/4479677/webpack-xades-test.zip)

**Comment by donskov** [comment]
I tried to use another bundler (https://parceljs.org/) and I see empty export:

![image](https://user-images.githubusercontent.com/9417251/79331723-4f0ca380-7f24-11ea-91a4-591faab4419e.png)

```ts
// index.ts
import 'regenerator-runtime/runtime';
import * as xades from 'xadesjs';

console.log(xades);
```

@microshine Could we find a way to resolve this problem?

**Comment by blaskurain** [comment]
I have found a workaround. It does work but for lack of a better word I would describe it as "sad". The trick is including the xades.js file verbatim in the HTML and taking care of a couple of things to ensure the library works and type checking is active.

First include the runtime, import the xadesjs library and declare a global variable ```XAdES```.
```typescript
import "regenerator-runtime/runtime";
import * as xadestypes from 'xadesjs';
declare var XAdES: any;
```
The variable's name must be XAdES (more about this later). xadestypes can't be used to do any work (it's an empty object) but it does have all the type information in it.

Second, load the xadesjs library by means of a ```script``` tag. I had to add the script at the end of the html file so that xadesjs sees the runtime. The ```XAdES``` variable of the previous step references the ```XAdES``` global created by the inclusion of the library, thus the name.

Third, ensure that the global variable ```XAdES``` gets initialized before using it. In this case I chose to wait for the ```DOMContentLoaded``` event before using it.

With all this in place you can use the library like this:
```typescript
const signedXml: xadestypes.SignedXml = new XAdES.SignedXml();
```
Use the imported ```xadestypes``` library to asign types to variables and the ```XAdES``` global to call the actual functions.

Full example attached.

[webpack-xades-test.zip](https://github.com/PeculiarVentures/xadesjs/files/4485603/webpack-xades-test.zip)

**Comment by microshine** [comment]
`xadesjs` module includes 3 types of precompiled files

### CommonJS
Required for NodeJS modules
```
build/index.js
```

### ES2015
Allows to use a file for bundlers (eg WebPack, Rollup)
```
build/index.es.js
```

### Browser
This type of file is ready for use it includes all required dependencies (instead of babel runtime) and compiled to ES5 format with IE11 supporting
```
build/xades.js
build/xades.min.js
```

I think you need to setup your bundler to prefer `module` link from `package.json` before `browser` and `main` links.
Something like that https://github.com/PeculiarVentures/xadesjs/blob/master/rollup.config.js#L53

About including babel runtime to xades.js. I don't like it cause:
- we don't need a runtime for NodeJS modules
- there can be a problem with multiple runtime libraries usage in browser.

**Comment by blaskurain** [comment]
That made the trick! Thank you very much.

Full example attached:

[webpack-xades-test.zip](https://github.com/PeculiarVentures/xadesjs/files/4486511/webpack-xades-test.zip)
